version: "3.1"

services:
  postgres:
    image: postgres:9.6
    networks:
      - inner_pandama

  redis:
    image: redis:6.2
    networks:
      - inner_pandama

  mongodb:
    image: mongo:5.0.5
    networks:
      - inner_pandama

  neo4j:
    image: neo4j/neo4j-arm64-experimental:4.1.0-arm64
    networks:
      - inner_pandama

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    networks:
      - inner_pandama

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - inner_pandama
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    networks:
      - inner_pandama
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.2
    networks:
      - inner_pandama
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.2
    networks:
      - inner_pandama
    depends_on:
      - elasticsearch

  celery_worker:
    image: pandama_celery_worker
    networks:
      - inner_pandama
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - mongodb
      - neo4j
      - elasticsearch
      - logstash
      - kibana

  celery_beat:
    image: pandama_celery_beat
    networks:
      - inner_pandama
    depends_on:
      - celery_worker

  web:
    image: pandama_web
    networks:
      - inner_pandama
      - outer_pandama
    depends_on:
      - celery_beat

  nginx:
    image: nginx:1.13
    depends_on:
      - web
    networks:
      - outer_pandama

networks:
  inner_pandama:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
  outer_pandama:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16