version: "3.1"

services:
  postgres:
    restart: always
    env_file: .env.compose.prod
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/initialization/sql_catalogs.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    restart: always
    env_file: .env.compose.prod
    command: redis-server --requirepass pandama
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  mongodb:
    restart: always
    env_file: .env.compose.prod
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  neo4j:
    image: neo4j:4.4.3
    restart: always
    env_file: .env.compose.prod
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data

  elasticsearch:
    restart: always
    env_file: .env.compose.prod
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  rabbitmq:
    restart: always
    env_file: .env.compose.prod
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./cert_rabbitmq:/cert_rabbitmq

  celery_worker:
    image: pandama_web
    restart: always
    env_file: .env.compose.prod
    command: bash ./wait-for-it.sh postgres:5432 -t 0 -s -- 
      sh -c "
      python3 manage.py makemigrations commons &&  
      python3 manage.py makemigrations customers &&  
      python3 manage.py makemigrations catalogs &&  
      python3 manage.py makemigrations carts &&  
      python3 manage.py makemigrations products &&  
      python3 manage.py makemigrations orders &&  
      python3 manage.py migrate && 
      celery -A config worker -c 1 --beat -l INFO"
    volumes:
      - .:/code

  celery_beat:
    image: pandama_web
    restart: always
    env_file: .env.compose.prod
    command: bash ./wait-for-it.sh postgres:5432 -t 0 -s -- 
      celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code

  web:
    image: pandama_web
    restart: always
    env_file: .env.compose.prod
    command: 
      bash ./wait-for-it.sh postgres:5432 -t 0 -s -- 
      gunicorn --bind :8000 config.wsgi
    volumes:
      - .:/code
    networks:
      - inner_pandama
      - outer_pandama

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - outer_pandama


networks:
  inner_pandama:
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
  outer_pandama:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
