import environ
env = environ.Env()

APM_SERVICE_NAME = env.str("APM_SERVICE_NAME", "pandama")
APM_SECRET_TOKEN= env.str("APM_SECRET_TOKEN")
APM_SERVER_URL = env.str("APM_SERVER_URL")
APM_SERVICE_DEBUG = env.bool("APM_SERVICE_DEBUG", True)

ELASTIC_APM = {
   'SERVICE_NAME': APM_SERVICE_NAME,
   'SECRET_TOKEN': APM_SECRET_TOKEN,
   'SERVER_URL': APM_SERVER_URL,
   'DEBUG': APM_SERVICE_DEBUG,
}