import environ

env = environ.Env()

DEBUG = env.bool('DEBUG', default=False)
SECRET_KEY = env.str('SECRET_KEY')
ALLOWED_HOSTS = env.str('ALLOWED_HOSTS', default=['*']).split(' ')

LOGTAIL_SOURCE_TOKEN=env.str('LOGTAIL_SOURCE_TOKEN')

PANDAMA_DOMAIN=env.str('PANDAMA_DOMAIN')
PANDAMA_PDP_PREURL=env.str('PANDAMA_PDP_PREURL', default='store/product-detail')

PAGE_SIZE_PRODUCT_LISTING = env.int('PAGE_SIZE_PRODUCT_LISTING', default=10)
PAGE_SIZE_HOME_PAGE_NEW_SECTION=env.int('PAGE_SIZE_HOME_PAGE_NEW_SECTION', default=6)
PAGE_SIZE_HOME_PAGE_TOP_SALE_SECTION=env.int('PAGE_SIZE_HOME_PAGE_TOP_SALE_SECTION', default=6)
PAGE_SIZE_PRODUCT_DETAIL_REVIEW=env.int('PAGE_SIZE_PRODUCT_DETAIL_REVIEW', default=5)
PAGE_SIZE_WISHLIST_LISTING=env.int('PAGE_SIZE_WISHLIST_LISTING', default=10)
PAGE_SIZE_ORDER_HISTORY=env.int('PAGE_SIZE_ORDER_HISTORY', default=5)
PAGE_SIZE_RECOMMENDED_PRODUCT=env.int('PAGE_SIZE_RECOMMENDED_PRODUCT', default=10)


AWS_ACCESS_KEY_ID=env.str('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY=env.str('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME=env.str('AWS_STORAGE_BUCKET_NAME', default='pandama')

S3_PRODUCT_IMAGE_FULL_URL_PREFIX=env.str('S3_PRODUCT_IMAGE_FULL_URL_PREFIX', default='https://pandama.s3.us-east-2.amazonaws.com/products/')
S3_PRODUCT_IMAGE_THUMBNAIL_URL_PREFIX=env.str('S3_PRODUCT_IMAGE_THUMBNAIL_URL_PREFIX', default='https://pandama.s3.us-east-2.amazonaws.com/products/')
S3_PDP_SCREENSHOT_URL_PREFIX=env.str('S3_PDP_SCREENSHOT_URL_PREFIX', default='https://pandama.s3.us-east-2.amazonaws.com/pdp_screens/')

LOTUS_STORE_PITTS=env.int('LOTUS_STORAGE_PITTS', default=83)
LOTUS_STORE_US_WEST=env.int('LOTUS_STORAGE_US_WEST', default=87)
LOTUS_STORE_US_EAST=env.int('LOTUS_STORAGE_US_EAST', default=84)
LOTUS_SINGLE_PRODUCT_API_URL_PREFIX=env.str('LOTUS_SINGLE_PRODUCT_API_URL_PREFIX', default='https://www.lotusfoodonline.com/mall/goods/')
LOTUS_PRODUCTS_BY_CATALOG_API_URL_PREFIX=env.str('LOTUS_PRODUCTS_BY_CATALOG_API_URL_PREFIX', default='https://www.lotusfoodonline.com/mall/goods/')

DYNAMIC_SYS_SETTINGS_KEY=env.str('DYNAMIC_SYS_SETTINGS_KEY', default='sys_configs')
DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_CATALOG_IDS=env.str('DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_CATALOG_IDS', default='SPIDER_PRODUCT_PROCESS_CATALOG_IDS')
DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_START_INDEX=env.str('DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_START_INDEX', default='SPIDER_PRODUCT_PROCESS_START_INDEX')
DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_BATCH_SIZE=env.str('DYNAMIC_SYS_SETTINGS_SPIDER_PRODUCT_PROCESS_BATCH_SIZE', default='SPIDER_PRODUCT_PROCESS_BATCH_SIZE')
DYNAMIC_SYS_SETTINGS_LOCKER_SPIDER_ASYNC_PROCESS=env.str('DYNAMIC_SYS_SETTINGS_LOCKER_SPIDER_ASYNC_PROCESS', default='LOCKER_SPIDER_ASYNC_PROCESS') # 1: lock, 0: unlock
DYNAMIC_SYS_SETTINGS_LOCKER_INDEX_ASYNC_PROCESS=env.str('DYNAMIC_SYS_SETTINGS_LOCKER_INDEX_ASYNC_PROCESS', default='LOCKER_INDEX_ASYNC_PROCESS') # 1: lock, 0: unlock


CHROMEDRIVER_PATH=env.str('CHROMEDRIVER_PATH', default='/app/.chromedriver/bin/chromedriver')
GOOGLE_CHROME_BIN=env.str('GOOGLE_CHROME_BIN', default='/app/.apt/usr/bin/google-chrome')